name: CI
"on": push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.3.0
      - run: npm install
